version: 0.2

phases:
  build:
    commands:
      - ls -la /codebuild/output/tmp/
      - ls -la
      - cat /codebuild/output/tmp/script.sh
      - ./gradlew bootJar

artifacts:
  files:
    - build/libs/*.jar

cache:
  paths:
    - '/root/.gradle/**/*'